//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ascension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class extraForms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal extraForms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ascension.extraForms", typeof(extraForms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to banish this Construct to take an additional turn?.
        /// </summary>
        internal static string BanishConstruct {
            get {
                return ResourceManager.GetString("BanishConstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Action.
        /// </summary>
        internal static string DoAction {
            get {
                return ResourceManager.GetString("DoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over!.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Power.
        /// </summary>
        internal static string OnePower {
            get {
                return ResourceManager.GetString("OnePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Rune.
        /// </summary>
        internal static string OneRune {
            get {
                return ResourceManager.GetString("OneRune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick card.
        /// </summary>
        internal static string PickCard {
            get {
                return ResourceManager.GetString("PickCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 1.
        /// </summary>
        internal static string Player1 {
            get {
                return ResourceManager.GetString("Player1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 2.
        /// </summary>
        internal static string Player2 {
            get {
                return ResourceManager.GetString("Player2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 3.
        /// </summary>
        internal static string Player3 {
            get {
                return ResourceManager.GetString("Player3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 4.
        /// </summary>
        internal static string Player4 {
            get {
                return ResourceManager.GetString("Player4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to do this?.
        /// </summary>
        internal static string WantToDo {
            get {
                return ResourceManager.GetString("WantToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may spend 4 runes to gain 3 honor.
        /// </summary>
        internal static string YggdrasilLabel {
            get {
                return ResourceManager.GetString("YggdrasilLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No thanks.
        /// </summary>
        internal static string YggdrasilNo {
            get {
                return ResourceManager.GetString("YggdrasilNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spend 4 runes.
        /// </summary>
        internal static string YggdrasilSpend {
            get {
                return ResourceManager.GetString("YggdrasilSpend", resourceCulture);
            }
        }
    }
}
