//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ascension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ascension.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy HI.
        /// </summary>
        internal static string BuyHI {
            get {
                return ResourceManager.GetString("BuyHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Mystic.
        /// </summary>
        internal static string BuyMystic {
            get {
                return ResourceManager.GetString("BuyMystic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  by .
        /// </summary>
        internal static string ByAmount {
            get {
                return ResourceManager.GetString("ByAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Row.
        /// </summary>
        internal static string CenterRow {
            get {
                return ResourceManager.GetString("CenterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructs.
        /// </summary>
        internal static string Constructs {
            get {
                return ResourceManager.GetString("Constructs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Hand.
        /// </summary>
        internal static string CurrentHand {
            get {
                return ResourceManager.GetString("CurrentHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck.
        /// </summary>
        internal static string Deck {
            get {
                return ResourceManager.GetString("Deck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Pile.
        /// </summary>
        internal static string DiscardPile {
            get {
                return ResourceManager.GetString("DiscardPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Turn.
        /// </summary>
        internal static string EndTurn {
            get {
                return ResourceManager.GetString("EndTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honor.
        /// </summary>
        internal static string Honor {
            get {
                return ResourceManager.GetString("Honor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment .
        /// </summary>
        internal static string Increment {
            get {
                return ResourceManager.GetString("Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Cultist.
        /// </summary>
        internal static string KillCultist {
            get {
                return ResourceManager.GetString("KillCultist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechana Runes .
        /// </summary>
        internal static string MechanaRunes {
            get {
                return ResourceManager.GetString("MechanaRunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Table.
        /// </summary>
        internal static string OnTable {
            get {
                return ResourceManager.GetString("OnTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play All.
        /// </summary>
        internal static string PlayAll {
            get {
                return ResourceManager.GetString("PlayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        internal static string Portal {
            get {
                return ResourceManager.GetString("Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runes.
        /// </summary>
        internal static string Runes {
            get {
                return ResourceManager.GetString("Runes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Void.
        /// </summary>
        internal static string TheVoid {
            get {
                return ResourceManager.GetString("TheVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Honor.
        /// </summary>
        internal static string YourHonor {
            get {
                return ResourceManager.GetString("YourHonor", resourceCulture);
            }
        }
    }
}
